return {
  "williamboman/mason.nvim",
  opts = {
    ensure_installed = {
      "clangd",
      "css-lsp",
      "debugpy",
      "docker-compose-language-service",
      "dockerfile-language-server",
      "goimports",
      "gopls",
      "html-lsp",
      "json-lsp",
      "lua-language-server",
      "mypy",
      "prettier",
      "pyright",
      "ruff",
      "rust-analyzer",
      "shfmt",
      "stylua",
      "tailwindcss-language-server",
      "typescript-language-server",
      -- "black",
      -- "flake8",
    },
  },
}
